apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipadshell
  namespace: ipadshell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipadshell
  template:
    metadata:
      labels:
        app: ipadshell
    spec:
      containers:
      - name: ipadshell
        image: us.icr.io/argo/ipadshell
        imagePullPolicy: Always
        ports:
        - containerPort: 3222
          protocol: TCP
        - containerPort: 32721
          protocol: UDP
        volumeMounts:
        - name: ipadshell-storage
          mountPath: /root/storage
      volumes:
      - name: ipadshell-storage
        persistentVolumeClaim:
          claimName: ipadshell-storage
