apiVersion: v1
kind: Service
metadata:
  name: ipadshell-udp
  namespace: ipadshell
spec:
  selector:
    app: ipadshell
  ports:
  - port: 32721
    name: mosh
    protocol: UDP
    nodePort: 32721
  type: NodePort