apiVersion: v1
kind: Service
metadata:
  name: ipadshell-udp
  namespace: ipadshell
spec:
  selector:
    app: ipadshell
  ports:
  - port: 60001
    name: mosh
    targetPort: 60001
    protocol: UDP
  type: LoadBalancer