apiVersion: v1
kind: Service
metadata:
  name: ipadshell
  namespace: ipadshell
spec:
  selector:
    app: ipadshell
  ports:
  - port: 3222
    name: ssh
    targetPort: 3222
    protocol: TCP
  loadBalancerIP: 169.47.157.120
  type: LoadBalancer